src/models/Site.php
<?php

namespace quoma\checkout\models;

use quoma\checkout\components\PlatformFactory;
use Yii;

/**
 * This is the model class for table "site".
 *
 * @property integer $site_id
 * @property string $name
 * @property string $server_name
 * @property string $status
 * @property string $image
 * @property string $admin_email
 *
 * @property SiteHasInstallment[] $siteHasInstallments
 * @property Installment[] $installments
 * @property SiteHasPaymentMethod[] $siteHasPaymentMethods
 * @property PaymentMethod[] $paymentMethods
 * @property Platform[] $platform
 * @property WebPayment[] $webPayments
 */
class Site extends \quoma\core\db\ActiveRecord {

    private $_installments;
    private $_paymentMethods;

    /**
     * @var UploadedFile
     */
    public $imageFile;

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'site';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb() {
        return Yii::$app->get('db_checkout');
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        $rules = [
            [['status', 'admin_email'], 'string'],
            [['status', 'name', 'server_name', 'admin_email', 'platform_id', 'platform_timeout'], 'required'],
            [['installments', 'paymentMethods', 'platform'], 'safe'],
            [['name'], 'string', 'max' => 45],
            [['server_name'], 'string', 'max' => 100],
            [['image'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg']
        ];

        return $rules;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'platform' => \quoma\checkout\CheckoutModule::t('Platform'),
            'site_id' => \quoma\checkout\CheckoutModule::t('Site'),
            'name' => \quoma\checkout\CheckoutModule::t('Name'),
            'server_name' => \quoma\checkout\CheckoutModule::t('Server Name'),
            'status' => \quoma\checkout\CheckoutModule::t('Status'),
            'siteHasInstallments' => 'SiteHasInstallments',
            'installments' => 'Installments',
            'siteHasPaymentMethods' => 'SiteHasPaymentMethods',
            'paymentMethods' => 'PaymentMethods',
            'platform' => \quoma\checkout\CheckoutModule::t('Platform'),
            'webPayments' => 'WebPayments',
            'admin_email' => \quoma\checkout\CheckoutModule::t('Admin Email'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiteHasInstallments() {
        return $this->hasMany(SiteHasInstallment::className(), ['site_id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInstallments() {
        return $this->hasMany(Installment::className(), ['installment_id' => 'installment_id'])->viaTable('site_has_installment', ['site_id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiteHasPaymentMethods() {
        return $this->hasMany(SiteHasPaymentMethod::className(), ['site_id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPaymentMethods() {
        return $this->hasMany(PaymentMethod::className(), ['payment_method_id' => 'payment_method_id'])->viaTable('site_has_payment_method', ['site_id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPaymentMethodTypes() {
        return $this->hasMany(PaymentMethodType::className(), ['payment_method_type_id' => 'payment_method_type_id'])->viaTable('payment_method_type_has_site', ['site_id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPaymentMethodTypeHasSite() {
        return $this->hasMany(PaymentMethodTypeHasSite::className(), ['site_id' => 'site_id']);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlatform() {
        return $this->hasOne(Platform::className(), ['platform_id' => 'platform_id']);
    }

    /**
     * Devuelve el experto de la plataforma de pago
     *
     * @return \class
     */
    public function loadPlatform(){

        $platform = $this->platform;
        $factory = new PlatformFactory();

        //busco plataformas que usa
        return $factory->getPlatform($platform);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWebPayments() {
        return $this->hasMany(WebPayment::className(), ['site_id' => 'site_id']);
    }

    /**
     * @brief Sets Installments relation on helper variable and handles events insert and update
     */
    public function setInstallments($installments) {

        if (empty($installments)) {
            $installments = [];
        }

        $this->_installments = $installments;

        $saveInstallments = function($event){
            $this->unlinkAll('installments', true);
            foreach ($this->_installments as $id) {
                $this->link('installments', Installment::findOne($id));
            }
        };

        $this->on(self::EVENT_AFTER_INSERT, $saveInstallments);
        $this->on(self::EVENT_AFTER_UPDATE, $saveInstallments);

    }


    /**
     * @brief Sets PaymentMethods relation on helper variable and handles events insert and update
     */
    public function setPaymentMethodsTypes($paymentMethodsTypes) {

        if (empty($paymentMethodsTypes)) {
            $paymentMethodsTypes = [];
        }


        $this->_paymentMethodsTypes = $paymentMethodsTypes;

        $savePaymentMethodsTypes = function($event){
            $this->unlinkAll('paymentMethodTypes', true);
            foreach ($this->_paymentMethodsTypes as $id) {
                $this->link('paymentMethodTypes', PaymentMethodType::findOne($id));
            }

        };

        $this->on(self::EVENT_AFTER_INSERT, $savePaymentMethodsTypes);
        $this->on(self::EVENT_AFTER_UPDATE, $savePaymentMethodsTypes);

    }

    /**
     * @brief Sets PaymentMethods relation on helper variable and handles events insert and update
     */
    public function setPaymentMethods($paymentMethods) {

        if (empty($paymentMethods)) {
            $paymentMethods = [];
        }


        $this->_paymentMethods = $paymentMethods;

        $savePaymentMethods = function($event){
            $this->unlinkAll('paymentMethods', true);
            foreach ($this->_paymentMethods as $id) {
                $this->link('paymentMethods', PaymentMethod::findOne($id), []);
            }

        };

        $this->on(self::EVENT_AFTER_INSERT, $savePaymentMethods);
        $this->on(self::EVENT_AFTER_UPDATE, $savePaymentMethods);

    }


    /**
     * @inheritdoc
     * Strong relations: WebPayments.
     */
    public function getDeletable() {
        if ($this->getWebPayments()->exists()) {
            return false;
        }
        return true;
    }

    /**
     * Rellena la relación con los id en lugar de objetos
     */
    public function fillPaymentMethods() {

        $select = [];

        $paymentMethods = $this->siteHasPaymentMethods;

        if ($paymentMethods)
            foreach ($paymentMethods as $model) {
                if (isset($model->payment_method_id))
                    $select[] = $model->payment_method_id;
                elseif (!is_object($model))
                    $select[] = $model;
            }

        return $select;
    }

    /**
     * Rellena la relación con los id en lugar de objetos
     */
    public function fillPaymentMethodTypes() {

        $select = [];

        $paymentMethodTypes = $this->paymentMethodTypeHasSite;

        if ($paymentMethodTypes)
            foreach ($paymentMethodTypes as $model) {
                if (isset($model->payment_method_type_id))
                    $select[] = $model->payment_method_type_id;
                elseif (!is_object($model))
                    $select[] = $model;
            }

        return $select;
    }

    /**
     * Rellena la relación con los id en lugar de objetos
     */
    public function findTimeOutPaymentMethodTypes($payment_method_type_id) {

        $paymentMethodType = $this->getPaymentMethodTypeHasSite()->andWhere(['payment_method_type_id' => $payment_method_type_id])->one();

        if ($paymentMethodType){
            return $paymentMethodType->time_out;
        }
        
        return NULL;
    }

    /**
     * Rellena la relación con los id en lugar de objetos
     */
    public function paymentMethodIsSelected($selected, $payment_method_id) {

        if ($selected)
            foreach ($selected as $id) {
                if ($id == $payment_method_id) {
                    return true;
                }
            }

        return false;
    }


    /**
     * Valida que el usuario haya seleccionado todas las relaciones necesarias
     */
    public function validateRelations($post) {

        if ($post['paymentMethods'] == '') {
            $this->addError('platform_id', 'Debe seleccionar los métodos de pago para la plataforma.');
            return false;
        }
        if (!isset($post['installments'])) {
            $this->addError('platform_id', 'Debe seleccionar las cuotas permitidas para la plataforma.');
            return false;
        }

        return true;
    }

    /**
     * @brief Deletes weak relations for this model on delete
     * Weak relations: None.
     */
    protected function unlinkWeakRelations() {
        $this->unlinkAll('paymentMethods', true);
        $this->unlinkAll('paymentMethodTypes', true);
        $this->unlinkAll('installments', true);
    }

    public static function getStatus() {
        return [
            'enabled' => \quoma\checkout\CheckoutModule::t('Enabled'),
            'disabled' => \quoma\checkout\CheckoutModule::t('Disabled'),
        ];
    }

    public function getLabelStatus() {
        return $this->getStatus()[$this->status];
    }

    /**

src/controllers/SiteController.php
<?php

namespace quoma\checkout\controllers;

use quoma\checkout\models\Platform;
use quoma\checkout\modules\siteConfig\models\SiteConfig;
use quoma\checkout\modules\siteConfig\models\SiteConfigCategory;
use quoma\checkout\modules\siteConfig\models\SiteConfigItem;
use quoma\modules\config\models\Config;
use Yii;
use quoma\checkout\models\Site;
use quoma\checkout\models\search\SiteSearch;
use quoma\core\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SiteController implements the CRUD actions for Site model.
 */
class SiteController extends Controller {


    /**
     * Lists all Site models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new SiteSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Site model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Site model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Site();

        if ($model->load(Yii::$app->request->post())) {

            $post = Yii::$app->request->post()['Site'];

            if ($model->validateRelations($post) && $model->save()) {

                return $this->redirect(['siteConfig/site-config/index', 'id' => $model->site_id]);
            }
        }
        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /*
     * 
     */

    public function actionGetConfig() {

        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $json = [];

        if ($post = \Yii::$app->request->post()) {

            if (isset($post['site_id']))
                $site = Site::findOne($post['site_id']);
            else
                $site = new Site();

            $platform = Platform::findOne($post['select']);

            $installments = \quoma\checkout\models\Installment::find()->all();

            $payment_methods = \quoma\checkout\models\PaymentMethod::find()->where(['platform_id' => $post['select']])->all();

            $payment_method_types = \quoma\checkout\models\PaymentMethodType::find()->all();

            $platform = Platform::findOne($post['select']);

            $json['status'] = 'success';
            $json['platform_id'] = $post['select'];
            $json['html'] = $this->renderPartial('partials/_view', [
                'model' => $site,
                'installments' => $installments,
                'payment_methods' => $payment_methods,
                'payment_method_types' => $payment_method_types,
                'platform' => $platform,
//                'platform_id' => $post['select'],
//                'site_has_platform' => $site_has_platform,
                'site_id' => (isset($post['site_id'])) ? $post['site_id'] : NULL,
            ]);

            return $json;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Updates an existing Site model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {

        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            $post = Yii::$app->request->post()['Site'];

            if ($model->validateRelations($post) && $model->save()) {

                return $this->redirect(['siteConfig/site-config/index', 'id' => $model->site_id]);
            }
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Site model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {

        $model = $this->findModel($id);
        $model->unlinkAll('installments', true);
        $model->unlinkAll('paymentMethods', true);

        $category = SiteConfigCategory::find()->where(['slug' => 'checkout-online', 'site_id' => $model->site_id])->one();

        $items = SiteConfigItem::getItems($category);

        foreach($items as $item){
            Site::getDb()->createCommand()->delete('site_config', [
                'site_config_item_id' => $item->site_config_item_id,
            ])->execute();

            Site::getDb()->createCommand()->delete('site_config_rule', [
                'site_config_item_id' => $item->site_config_item_id,
            ])->execute();

            $item->delete();
        }
        $category->delete();
        $model->delete();

        return $this->redirect(['index']);
    }


    /**
     * Finds the Site model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Site the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Site::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

src/views/site/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */


?>

    <div class="site-form">

        <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

        <div class="col-lg-6 ">
            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-lg-6 ">
            <?= $form->field($model, 'admin_email')->textInput(['maxlength' => true]) ?>
        </div>

        <div class="col-lg-6 ">
            <?= $form->field($model, 'server_name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-lg-6 ">
            <?= $form->field($model, 'status')->dropDownList(['enabled' => quoma\checkout\CheckoutModule::t('Enabled'), 'disabled' => quoma\checkout\CheckoutModule::t('Disabled'),]) ?>
        </div>

            <?= $form->field($model, 'platform_id')->widget(Select2::classname(), [
                'data' => \yii\helpers\ArrayHelper::map(\quoma\checkout\models\Platform::find()->where('status="enabled"')->all(), 'platform_id', 'name'),
                'language' => 'es',
                'options' => ['id' => 'platform-select', 'placeholder' => 'Seleccione una plataforma...'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]); ?>
            <div id="config_platform">
                <?php if (!$model->isNewRecord): ?>
                    <?= $this->render('partials/_view', [
                        'model' => $model,
                        'payment_methods' => $model->platform->paymentMethods,
                        'installments' => \quoma\checkout\models\Installment::find()->all(),
                        'platform' => $model->platform,
                    ]) ?>
                <?php endif; ?>
            </div>

            <div class="form-group<?php if ($model->hasErrors('paymentMethods')) echo ' has-error' ?>">

            </div>

        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?></div>

        <?php ActiveForm::end(); ?>

    </div>

    <script>

        var Platforms = new function () {

            this.init = function () {

                $(document).ready(function () {


                    var platform_id =  $("#platform-select").val();

                    if(platform_id){

                        var data = new Object;
                        data.select = platform_id;
                        data.site_id = <?= ($model->site_id) ? $model->site_id : NULL ?>

                            getConfig(data);

                    }


                    $('#platform-select').on('change', function () {

                        var data = new Object;
                        data.select = $(this).val();
                        <?php if(!$model->isNewRecord):?>
                        data.site_id = <?= $model->site_id?>
                        <?php endif;?>

                            getConfig(data);

                    });
                });
            };


            function getConfig(data){
                $.ajax({
                    url: '<?= yii\helpers\Url::toRoute(['site/get-config']); ?>',
                    data: data,
                    dataType: 'json',
                    type: 'post'
                }).done(function (json) {
                    if (json.status === 'success') {
                        $('#config_platform').html(json.html);
                    }
                });
            }
        };


    </script>

<?php
$this->registerJs('Platforms.init();');

        

src/views/site/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\checkout\models\search\SiteSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="site-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'site_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'server_name') ?>

    <?= $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

src/views/site/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\checkout\models\Site */

$this->title = Yii::t('app', 'Create').' '. quoma\checkout\CheckoutModule::t('Site');
$this->params['breadcrumbs'][] = ['label' => quoma\checkout\CheckoutModule::t('Sites'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

src/views/site/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use quoma\checkout\CheckoutModule;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\checkout\models\search\SiteSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = CheckoutModule::t('Sites');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-index">
    <div class="title">
        <h1><?= Html::encode($this->title) ?></h1>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

        <p>
            <?= Html::a("<span class='glyphicon glyphicon-plus'></span> " . Yii::t('app', 'Create') . ' ' . 
                    CheckoutModule::t('Site'), ['create'], ['class' => 'btn btn-success']) ?>
        </p>
    </div>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'name',
            'server_name',
            [
                'attribute' => 'status',
                'value' => function($data) {
                    return (!empty($data->status) ) ? $data->getLabelStatus() : '-';
                },
                'filter' => \quoma\checkout\models\Site::getStatus(),
            ],
            ['class' => 'quoma\core\grid\ActionColumn'],
        ],
    ]);
    ?>

</div>

src/views/site/site_config.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;



/* @var $this yii\web\View */
/* @var $model app\modules\checkout\models\Site */

$this->title = Yii::t('app', 'Create').' '. quoma\checkout\CheckoutModule::t('Site');
$this->params['breadcrumbs'][] = ['label' => quoma\checkout\CheckoutModule::t('Sites'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="config-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'item_id')->textInput() ?>

    <?= $form->field($model, 'value')->textarea(['rows' => 6]) ?>



    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

src/views/site/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\checkout\models\Site */

$this->title = Yii::t('app', 'Update') .' '. quoma\checkout\CheckoutModule::t('Site'). ' ' . $model->name;

$this->params['breadcrumbs'][] = ['label' => quoma\checkout\CheckoutModule::t('Site'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->site_id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="site-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

src/views/site/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\checkout\models\Site */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => quoma\checkout\CheckoutModule::t('Sites'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-view">
    <div class="title">
        <h1><?= Html::encode($this->title) ?></h1>

        <p>
            <?= Html::a("<span class='glyphicon glyphicon-pencil'></span> " . Yii::t('app', 'Update'),
                    ['update', 'id' => $model->site_id], ['class' => 'btn btn-primary']) ?>
            <?php if($model->deletable)
                echo Html::a("<span class='glyphicon glyphicon-remove'></span> " . Yii::t('app', 'Delete'), ['delete', 'id' => $model->site_id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]) ?>
        </p>
    </div>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
            'admin_email',
            'server_name',
            [
                'attribute'=>'status',
                'value'=> (!empty($model->status) ) ? $model->getLabelStatus() : '-',
            ],
            [
                'label' => 'Imagen',
                'attribute' => 'image',
//                'value' => Yii::$app->getModule('equipment')->basePath . $model->image,
                'value' =>  $model->image,
                'format' => ['image',['width'=>'500','height'=>'500']],
                'visible' => ($model->image) ? true : false
            ],
        ],
    ]) ?>

</div>